# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.9.4

jobs:
  build_deploy:
    <<: *defaults
    steps:
      - checkout

      # prep aws cli
      #- run: echo 'export PATH=~/.local/bin:$PATH' >> $BASH_ENV
      #- run: mkdir ~/.aws
      #- run: echo -e "[profile development-ci]\nrole_arn=arn:aws:iam::942882936269:role/development-ci\ncredential_source=Environment" > ~/.aws/config

      # set the NPM token so we can read private packages
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_USER_TOKEN" >> ~/.npmrc

      # build packages
      - run: npm install
      - run: npm run bootstrap
      - run: npm run build

      # run tests
      - run: npm run test

      # deploy
      #- run: npm run deploy:development

      # set the NPM token so we can publish
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_ADMIN_TOKEN" >> ~/.npmrc

      # publish
      - run: npm run publish:patch

workflows:
  version: 2
  main:
    jobs:
      - build_deploy:
          context: default
          filters:
            branches:
              only:
                - master
